version: "3.4"
services:
    ollama:
      image: ollama/ollama:latest
      restart: always
      ports:
        - "11434:11434"
      volumes:
       - /opt/innodisk/accelbrain/ollama:/root/.ollama
    open-webui:
      image: innodiskorg/open-webui:latest
      container_name: open-webui
      restart: always
      network_mode: host
      volumes:
       - /opt/innodisk/accelbrain/open-webui:/app/backend/data
      environment:
        - OLLAMA_BASE_URL=http://127.0.0.1:11434